#pragma once

// Comment this out if SAR namespaces should be scoped
#define SEQARC_INLINE

#ifdef SEQARC_INLINE
#define NAMESPACE_ATTRIBUTE inline
#else
#define NAMESPACE_ATTRIBUTE
#endif

namespace SeqArc {

	enum {
		Count = 41,
		SfxCount = 449,
	};

	namespace FirstID {
		enum {
			SAR_COURSE					= 0,
			SAR_MENU					= 18,
			SAR_KOOPAJR					= 52,
			SAR_VOLCANO					= 62,
			SAR_MARIO_BASE				= 68,
			SAR_VS						= 75,
			SAR_THUNDER					= 86,
			SAR_HUGE_KURIBO				= 94,
			SAR_TORNADO					= 102,
			SAR_VS_COMMON_ENEMY_01		= 104,
			SAR_OBJ_TEKKYU				= 106,
			SAR_ENEMY_BASE				= 110,
			SAR_ENEMY_01				= 125,
			SAR_ENEMY_02				= 127,
			SAR_ENEMY_03				= 128,
			SAR_ENEMY_04				= 145,
			SAR_ENEMY_05				= 157,
			SAR_ENEMY_06				= 162,
			SAR_ENEMY_GOREM				= 175,
			SAR_ENEMY_GABON				= 179,
			SAR_BOSS_PAKKUN				= 186,
			SAR_SABAKU_BOSS				= 194,
			SAR_VS_COMMON_MARIO_BASE	= 199,
			SAR_OLD_KOOPA				= 208,
			SAR_VS_PREDOWNLOAD			= 228,
			SAR_VS_COMMON_MENU			= 229,
			SAR_ENEMY_DOSSY				= 241,
			SAR_OBJ_FENCE				= 242,
			SAR_OPENING_DEMO			= 245,
			SAR_PLAYER_BASE				= 278,
			SAR_LUIGI_BASE				= 320,
			SAR_VS_COMMON_PLAYER_BASE	= 327,
			SAR_VS_COMMON_LUIGI_BASE	= 384,
			SAR_ITEM_HOUSE				= 393,
			SAR_KOOPAJR_COMMON			= 400,
			SAR_PIPE_CANNON				= 413,
			SAR_LAST_KOOPA_DOOR			= 418,
			SAR_LAST_KOOPA_DEMO			= 421,
			SAR_BOSS_COMMON				= 430,
			SAR_BOSS_CHOROPU			= 439,
			SAR_OBJ_CORK				= 447,
		};
	};


	NAMESPACE_ATTRIBUTE namespace SAR_COURSE {
		enum {
			SE_PLY_CLIMB_ROPE = FirstID::SAR_COURSE,
			SE_PLY_WALK_ON_ROPE,
			SE_PLY_MONKEY_BARS,
			SE_PLY_TARZAN_ROPE,
			SE_EMY_WANWAN_BARK,
			SE_EMY_WANWAN_GACHI,
			SE_EMY_WANWAN_KUSARI,
			SE_OBJ_SWITCH_APP,
			SE_OBJ_STEP_ON_SWITCH,
			SE_OBJ_LIFT_TENBIN,
			SE_OBJ_TURN_LIFT,
			SE_OBJ_FLIPPER,
			SE_OBJ_DOOR_OPEN,
			SE_OBJ_DOOR_CLOSE,
			SE_OBJ_BDOOR_OPEN,
			SE_OBJ_BDOOR_CLOSE,
			SE_SYS_SWITCH_CT,
			SE_SYS_SWITCH_CT_LAST,
		};
	};

	NAMESPACE_ATTRIBUTE namespace SAR_MENU {
		enum {
			SE_PLY_FOOTNOTE = FirstID::SAR_MENU,
			SE_PLY_FOOTNOTE_DOKAN,
			SE_PLY_FOOTNOTE_SAND,
			SE_PLY_FOOTNOTE_SNOW,
			SE_PLY_ARRIVE_POINT,
			SE_PLY_MAP_JUMP,
			SE_PLY_DOKAN_IN_OUT,
			SE_EMY_HMBR_WALK,
			SE_EMY_MAP_KPJR_FOOT,
			SE_EMY_MAP_KPJR_JUMP,
			SE_OBJ_PTBK_MOVE,
			SE_OBJ_SHIRO_BOYON,
			SE_OBJ_STAR_COIN_BOARD,
			SE_OBJ_KINO_HOUSE_APP,
			SE_OBJ_KINO_HOUSE_DISAPP,
			SE_OBJ_NEW_ROAD,
			SE_OBJ_BRIDGE_APP,
			SE_OBJ_MAP_FLAG_HATAMEKI,
			SE_OBJ_YOUGAN_ABUKU,
			SE_OBJ_BOARD_OFF,
			SE_OBJ_BOARD_DISAPP,
			SE_VOC_MAP_P_HELP,
			SE_AMB_EARTHQUAKE,
			SE_AMB_SEA_WAVE,
			SE_AMB_SABAKU_WIND,
			SE_AMB_YOUGAN,
			SE_SYS_COURSE_IN,
			SE_SYS_COURSE_IN_L,
			SE_SYS_ZOOM_OUT,
			SE_SYS_ZOOM_IN,
			SE_SYS_WORLD_CHG,
			SE_SYS_NEW_POINT,
			SE_SYS_NEW_POINT_END,
			SE_SYS_SCROLL_COMAND,
		};
	};

	NAMESPACE_ATTRIBUTE namespace SAR_KOOPAJR {
		enum {
			SE_EMY_KPJR_DAMAGE_V = FirstID::SAR_KOOPAJR,
			SE_EMY_KPJR_CRY_V,
			SE_EMY_KPJR_UH,
			SE_EMY_KPJR_LAND,
			SE_EMY_KPJR_JITABATA,
			SE_EMY_KPJR_GUARD_ON,
			SE_EMY_KPJR_GUARDING,
			SE_EMY_KPJR_GUARD_OFF,
			SE_EMY_KPJR_DAMAGE,
			SE_EMY_KPJR_PURUPURU,
		};
	};

	NAMESPACE_ATTRIBUTE namespace SAR_VOLCANO {
		enum {
			SE_EMY_HANABI_IGNITION = FirstID::SAR_VOLCANO,
			SE_EMY_HANABI_TAME,
			SE_OBJ_HANABI_HYU,
			SE_OBJ_HANABI_DON,
			SE_OBJ_ROCK,
			SE_AMB_ERUPT,
		};
	};

	NAMESPACE_ATTRIBUTE namespace SAR_MARIO_BASE {
		enum {
			SE_PLY_WDOKAN_SHOT = FirstID::SAR_MARIO_BASE,
			SE_PLY_CANNON_SHOT,
			SE_VOC_MA_OTOTO,
			SE_VOC_MA_WOOO,
			SE_VOC_MA_CLIMB,
			SE_VOC_MA_HOH,
			SE_VOC_MA_DANGLE,
		};
	};

	NAMESPACE_ATTRIBUTE namespace SAR_VS {
		enum {
			SE_PLY_WARP = FirstID::SAR_VS,
			SE_PLY_FB_FROM_LUIGI,
			SE_PLY_FB_FROM_MARIO,
			SE_PLY_PLAYER_FUMU,
			SE_OBJ_DOKAN_APP,
			SE_EMY_FUWA_FUMU_L,
			SE_SYS_VS_COUNT,
			SE_SYS_VS_COUNT_LAST,
			SE_SYS_VS_STAR_GET,
			SE_SYS_VS_STAR_DENIED,
			SE_SYS_VS_STAR_APP,
		};
	};

	NAMESPACE_ATTRIBUTE namespace SAR_THUNDER {
		enum {
			SE_EMY_ELCJ_PRE_DIVE = FirstID::SAR_THUNDER,
			SE_EMY_ELCJ_DIVE,
			SE_EMY_PIPO_BOUND,
			SE_EMY_ELCJ_APP,
			SE_EMY_ELCJ_CHARGE,
			SE_EMY_ELCJ_THROW,
			SE_EMY_ELCJ_DOWN,
			SE_AMB_THUNDER,
		};
	};

	NAMESPACE_ATTRIBUTE namespace SAR_HUGE_KURIBO {
		enum {
			SE_EMY_KURI_CHANGE_BIG = FirstID::SAR_HUGE_KURIBO,
			SE_EMY_BIG_KURIBO_WALK,
			SE_EMY_BIG_KURIBO_DAMAGE,
			SE_EMY_BIG_KURIBO_DOWN,
			SE_EMY_BIG_KURIBO_DESITION,
			SE_EMY_BIG_KURIBO_SMOKE,
			SE_EMY_BK_FUMARE_BY_HUGE,
			SE_EMY_CHIBI_KURI_WALK,
		};
	};

	NAMESPACE_ATTRIBUTE namespace SAR_TORNADO {
		enum {
			SE_PLY_JUMP_OUT = FirstID::SAR_TORNADO,
			SE_AMB_TORNADO,
		};
	};

	NAMESPACE_ATTRIBUTE namespace SAR_VS_COMMON_ENEMY_01 {
		enum {
			SE_EMY_KILLER_SHOT = FirstID::SAR_VS_COMMON_ENEMY_01,
			SE_EMY_BH_BOMB,
		};
	};

	NAMESPACE_ATTRIBUTE namespace SAR_OBJ_TEKKYU {
		enum {
			SE_OBJ_TEKKYU_ROLL = FirstID::SAR_OBJ_TEKKYU,
			SE_OBJ_TEKKYU_CRASH,
			SE_OBJ_BIG_ROCK_CRASH,
			SE_OBJ_BIG_ROCK_ROLL,
		};
	};

	NAMESPACE_ATTRIBUTE namespace SAR_ENEMY_BASE {
		enum {
			SE_EMY_KURIBO_FUMU = FirstID::SAR_ENEMY_BASE,
			SE_EMY_KAME_FUMU,
			SE_EMY_KAME_KERU,
			SE_EMY_KAME_HIT_1,
			SE_EMY_KAME_HIT_2,
			SE_EMY_KAME_HIT_3,
			SE_EMY_KAME_HIT_4,
			SE_EMY_KAME_HIT_5,
			SE_EMY_KAME_HIT_6,
			SE_EMY_KAME_HIT_7,
			SE_EMY_PAKKUN_MOUTH,
			SE_EMY_PAKKUN_MOUTH_2,
			SE_EMY_PAKKUN_DAMAGE,
			SE_EMY_PAKKUN_DOWN,
			SE_OBJ_ITEM_DISAPP,
		};
	};

	NAMESPACE_ATTRIBUTE namespace SAR_ENEMY_01 {
		enum {
			SE_EMY_JUGEM_APP = FirstID::SAR_ENEMY_01,
			SE_OBJ_PAIPO,
		};
	};

	NAMESPACE_ATTRIBUTE namespace SAR_ENEMY_02 {
		enum {
			SE_EMY_WAKABA_APP = FirstID::SAR_ENEMY_02,
		};
	};

	NAMESPACE_ATTRIBUTE namespace SAR_ENEMY_03 {
		enum {
			SE_PLY_BURN_DOWN = FirstID::SAR_ENEMY_03,
			SE_PLY_BURN_DOWN_L,
			SE_PLY_TOUCH_BIRI,
			SE_OBJ_UKISHIMA_S,
			SE_OBJ_UKISHIMA_L,
			SE_OBJ_SNAKE_BLOCK,
			SE_OBJ_BURNER,
			SE_OBJ_BURNER_LEVEL,
			SE_EMY_KALON,
			SE_EMY_BATTAN_WALK,
			SE_EMY_BATTAN_FALLDOWN,
			SE_EMY_BATTAN_BREAK,
			SE_EMY_BUBBLE,
			SE_EMY_BUBBLE_IN,
			SE_EMY_KALON_REVIVAL,
			SE_VOC_BIRI,
			SE_VOC_BIRI_L,
		};
	};

	NAMESPACE_ATTRIBUTE namespace SAR_ENEMY_04 {
		enum {
			SE_EMY_UTSUBO = FirstID::SAR_ENEMY_04,
			SE_EMY_BIG_UTSUBO,
			SE_EMY_BAKU_SUCK,
			SE_EMY_BAKU_PAKU,
			SE_EMY_UTSUBO_POUNCE,
			SE_EMY_MENBO_SHOOT,
			SE_OBJ_BOMB_FLASH,
			SE_OBJ_MENBO_BOMB,
			SE_VOC_BAKU_EATEN,
			SE_VOC_BAKU_EATEN_L,
			SE_AMB_DOKAN_AWA,
			SE_AMB_WATER_TORNADO,
		};
	};

	NAMESPACE_ATTRIBUTE namespace SAR_ENEMY_05 {
		enum {
			SE_EMY_GAMA_FUMARE = FirstID::SAR_ENEMY_05,
			SE_EMY_GAMA_LAST,
			SE_EMY_GAMA_JUMP,
			SE_EMY_GASA_APPEAR,
			SE_EMY_GASA_FOOT,
		};
	};

	NAMESPACE_ATTRIBUTE namespace SAR_ENEMY_06 {
		enum {
			SE_EMY_TERESA = FirstID::SAR_ENEMY_06,
			SE_EMY_KABO_HIBI,
			SE_EMY_KABO_BREAK,
			SE_EMY_BASABASA,
			SE_EMY_FO_FADE_AWAY,
			SE_EMY_FO_GLOW_UP,
			SE_EMY_FO_CHASE,
			SE_EMY_KNUCKLER,
			SE_OBJ_LIFT_GATAGATA,
			SE_OBJ_LIFT_KYUKOKA,
			SE_OBJ_LIFT_KYUJYOSHO,
			SE_OBJ_MANHOLE_LAND,
			SE_OBJ_MANHOLE_ROLLING,
		};
	};

	NAMESPACE_ATTRIBUTE namespace SAR_ENEMY_GOREM {
		enum {
			SE_EMY_GOREM_BLOCK = FirstID::SAR_ENEMY_GOREM,
			SE_EMY_GOREM_FOOT,
			SE_EMY_GOREM_JUMP,
			SE_EMY_GOREM_APP,
		};
	};

	NAMESPACE_ATTRIBUTE namespace SAR_ENEMY_GABON {
		enum {
			SE_EMY_YUKIDAMA_APP = FirstID::SAR_ENEMY_GABON,
			SE_EMY_GABON_THROW,
			SE_OBJ_SNOW_FALL,
			SE_OBJ_YUKIDAMA_BREAK,
			SE_OBJ_YUKIDAMA_ROLL,
			SE_VOC_MA_BURIED_IN_SNOW,
			SE_VOC_LU_BURIED_IN_SNOW,
		};
	};

	NAMESPACE_ATTRIBUTE namespace SAR_BOSS_PAKKUN {
		enum {
			SE_EMY_BP_UPSIDE_DOWN = FirstID::SAR_BOSS_PAKKUN,
			SE_EMY_BP_BREATHE_IN,
			SE_EMY_BP_BREATHE_OUT,
			SE_EMY_BP_FLAP,
			SE_EMY_BP_SLIP,
			SE_EMY_BP_PIYO,
			SE_EMY_BP_DAMAGE,
			SE_EMY_BP_ATTACK,
		};
	};

	NAMESPACE_ATTRIBUTE namespace SAR_SABAKU_BOSS {
		enum {
			SE_EMY_SB_PREAPP = FirstID::SAR_SABAKU_BOSS,
			SE_EMY_SB_APP,
			SE_EMY_SB_DISAPP,
			SE_EMY_SB_SHOOT,
			SE_EMY_SB_DOWN,
		};
	};

	NAMESPACE_ATTRIBUTE namespace SAR_VS_COMMON_MARIO_BASE {
		enum {
			SE_PLY_SPIN_JUMP_M = FirstID::SAR_VS_COMMON_MARIO_BASE,
			SE_PLY_KABE_KICK,
			SE_PLY_KABE_KICK_1,
			SE_PLY_KABE_KICK_2,
			SE_PLY_CHANGE_BIGGEST,
			SE_VOC_MA_JUMP_03,
			SE_VOC_MA_WIN,
			SE_VOC_MA_THROW,
			SE_VOC_MA_THROW_1,
		};
	};

	NAMESPACE_ATTRIBUTE namespace SAR_OLD_KOOPA {
		enum {
			SE_EMY_OLKP_FOOT = FirstID::SAR_OLD_KOOPA,
			SE_EMY_HNKP_FOOT,
			SE_EMY_OLKP_JITABATA,
			SE_EMY_OLKP_FALL_DOWN,
			SE_EMY_OLKP_IN_LAVA,
			SE_EMY_HNKP_DOWN,
			SE_EMY_OLKP_APP,
			SE_EMY_OLKP_LAND,
			SE_EMY_HNKP_APP_LAND,
			SE_EMY_HNKP_LAND,
			SE_EMY_HNKP_UNITE,
			SE_EMY_OLKP_BARK,
			SE_EMY_OLKP_GOBOGOBO,
			SE_EMY_OLKP_DAMAGE,
			SE_EMY_OLKP_FUMARE,
			SE_EMY_OLKP_FIRE,
			SE_EMY_OLKP_CRY,
			SE_EMY_OLKP_CRY_FO,
			SE_OBJ_HONE_HIT_KOURA,
			SE_EMY_OLKP_FIRE_SHOT,
		};
	};

	NAMESPACE_ATTRIBUTE namespace SAR_VS_PREDOWNLOAD {
		enum {
			SE_SYS_PREDOWNLOAD = FirstID::SAR_VS_PREDOWNLOAD,
		};
	};

	NAMESPACE_ATTRIBUTE namespace SAR_VS_COMMON_MENU {
		enum {
			SE_SYS_CURSOR = FirstID::SAR_VS_COMMON_MENU,
			SE_SYS_WINDOW_OPEN,
			SE_SYS_WINDOW_CLOSE,
			SE_SYS_NINTENDO_LOGO,
			SE_SYS_DECIDE,
			SE_SYS_BACK,
			SE_SYS_PAUSE,
			SE_SYS_CAMERA_MOVE,
			SE_SYS_STAR_COIN_DEC,
			SE_SYS_WARNING,
			SE_SYS_SLEEP_IN,
			SE_SYS_SLEEP_OUT,
		};
	};

	NAMESPACE_ATTRIBUTE namespace SAR_ENEMY_DOSSY {
		enum {
			SE_OBJ_DOSSY_SWIM = FirstID::SAR_ENEMY_DOSSY,
		};
	};

	NAMESPACE_ATTRIBUTE namespace SAR_OBJ_FENCE {
		enum {
			SE_PLY_WALK_METAL = FirstID::SAR_OBJ_FENCE,
			SE_OBJ_FENCE_TURN_S,
			SE_OBJ_FENCE_TURN_L,
		};
	};

	NAMESPACE_ATTRIBUTE namespace SAR_OPENING_DEMO {
		enum {
			SE_VOC_OPDM_YES = FirstID::SAR_OPENING_DEMO,
			SE_VOC_OPDM_UN_01,
			SE_VOC_OPDM_UN_01_L,
			SE_VOC_OPDM_UN_02,
			SE_VOC_OPDM_UN_02_L,
			SE_VOC_OPDM_AWAWA_01,
			SE_VOC_OPDM_AWAWA_01_L,
			SE_VOC_OPDM_AWAWA_02,
			SE_VOC_OPDM_AWAWA_02_L,
			SE_VOC_OPDM_AWAWA_03,
			SE_VOC_OPDM_HOEE,
			SE_VOC_LUIGI_DECIDE,
			SE_AMB_OPDM_WARBLE,
			SE_AMB_OPDM_THUNDER,
			SE_AMB_OPDM_BABEL,
			SE_EMY_OPDM_KPJR_FOOT,
			SE_EMY_OPDM_JUGEM_APP,
			SE_PLY_OPDM_MA_FOOT,
			SE_PLY_OPDM_MA_JUMP,
			SE_PLY_OPDM_MA_BRAKE,
			SE_PLY_OPDM_MA_HIT,
			SE_VOC_OPDM_PEACH_CRY,
			SE_VOC_OPDM_PEACH_HELP,
			SE_VOC_OPDM_PEACH_OH,
			SE_OBJ_OPDM_NEW_FALL,
			SE_OBJ_OPDM_NEW_SET,
			SE_OBJ_OPDM_LOGO_FALL_L,
			SE_OBJ_OPDM_LOGO_FALL_S,
			SE_SYS_FILE_SELECTED,
			SE_SYS_FILE_COPYING,
			SE_SYS_FILE_COPY_END,
			SE_SYS_FILE_DELETING,
			SE_SYS_FILE_DELETE_END,
		};
	};

	NAMESPACE_ATTRIBUTE namespace SAR_PLAYER_BASE {
		enum {
			SE_PLY_CANNON_READY = FirstID::SAR_PLAYER_BASE,
			SE_PLY_CANNON_BACK_SHOT,
			SE_PLY_PUNCH,
			SE_PLY_KICK,
			SE_PLY_LAND,
			SE_PLY_SHUFFLE,
			SE_PLY_GLIDING,
			SE_PLY_GLIDING_END,
			SE_OBJ_PUFF_MUSH,
			SE_OBJ_PUFF_MUSH_2,
			SE_OBJ_PUFF_MUSH_3,
			SE_OBJ_PUFF_MUSH_4,
			SE_OBJ_PUFF_MUSH_LAST,
			SE_OBJ_GET_DRAGON_COIN,
			SE_OBJ_STORE_STAR_COIN,
			SE_OBJ_FIREBALL_DISAPP,
			SE_OBJ_BLOCK_KICK,
			SE_OBJ_GET_THUNDER,
			SE_OBJ_GOAL_HANABI,
			SE_OBJ_GET_RED_COIN,
			SE_OBJ_COIN_SUBSTANT,
			SE_OBJ_FLAG_HATAMEKI,
			SE_OBJ_TATE_KINO_DOWN,
			SE_OBJ_YOKO_KINO_EXPAND,
			SE_OBJ_YOKO_KINO_CONST,
			SE_OBJ_SISO_KINO,
			SE_OBJ_TATE_KINO_UP,
			SE_OBJ_TSUTA_APPEAR,
			SE_OBJ_BLOCK_EXTEND,
			SE_EMY_FUWA_FUMU,
			SE_EMY_DOWN_BY_PUNCH,
			SE_EMY_HAMMER,
			SE_EMY_BOOMERANG,
			SE_EMY_HONE,
			SE_VOC_MA_GET_ITEM,
			SE_VOC_MA_GET_ITEM_2,
			SE_SYS_MID_POINT,
			SE_SYS_SLOT,
			SE_SYS_CORRECT,
			SE_SYS_INCORRECT,
			SE_SYS_HURRY_UP,
			SE_SYS_GOAL_FLAG,
		};
	};

	NAMESPACE_ATTRIBUTE namespace SAR_LUIGI_BASE {
		enum {
			SE_PLY_WDOKAN_SHOT_L = FirstID::SAR_LUIGI_BASE,
			SE_PLY_CANNON_SHOT_L,
			SE_VOC_LU_OTOTO,
			SE_VOC_LU_WOOO,
			SE_VOC_LU_CLIMB,
			SE_VOC_LU_HOH,
			SE_VOC_LU_DANGLE,
		};
	};

	NAMESPACE_ATTRIBUTE namespace SAR_VS_COMMON_PLAYER_BASE {
		enum {
			SE_PLY_JUMP = FirstID::SAR_VS_COMMON_PLAYER_BASE,
			SE_PLY_JUMP_2,
			SE_PLY_JUMP_3,
			SE_PLY_JUMP_4,
			SE_PLY_SLIP,
			SE_PLY_SLIP_W,
			SE_PLY_HIP_ATTACK,
			SE_PLY_HIP_ATTACK_H,
			SE_PLY_HIP_ATTACK_M,
			SE_PLY_CLASH,
			SE_PLY_CLASH_2,
			SE_PLY_DOWN,
			SE_PLY_SWIM,
			SE_PLY_FOOTNOTE_N,
			SE_PLY_FOOTNOTE_F,
			SE_PLY_FOOTNOTE_SD,
			SE_PLY_FOOTNOTE_SN,
			SE_PLY_DRILL,
			SE_PLY_QUAT,
			SE_PLY_KOURA_QUAT,
			SE_PLY_FOOTNOTE_H,
			SE_PLY_FOOTNOTE_MW,
			SE_OBJ_TRAMPOLINE_JUMP,
			SE_OBJ_TRAMPOLINE_JUMP2,
			SE_PLY_POLE_SLIDE,
			SE_PLY_POLE_CLIMB,
			SE_PLY_ICE_SLIP,
			SE_PLY_KOURA_SLIDE,
			SE_PLY_CHANGE_BIG,
			SE_PLY_LAND_WATER,
			SE_PLY_LAND_WATER_M,
			SE_PLY_CHANGE_NORMAL,
			SE_PLY_CHANGE_MAME,
			SE_PLY_THROW_FIRE,
			SE_PLY_ROLLING,
			SE_PLY_CHANGE_SMALL,
			SE_PLY_HIT_BLOCK,
			SE_OBJ_GET_COIN,
			SE_OBJ_KOOPA_CORPSE,
			SE_OBJ_BOARD_REVERSE,
			SE_OBJ_KOURA,
			SE_OBJ_COIN_BOUND,
			SE_OBJ_DOKAN_BREAK,
			SE_PLY_JUMPDAI,
			SE_OBJ_SPRAY,
			SE_OBJ_ITEM_APPEAR,
			SE_OBJ_HUGE_KINO_APP,
			SE_OBJ_GOOD_ITEM_APPEAR,
			SE_OBJ_BLOCK_BREAK,
			SE_PLY_STAR_ATTACK,
			SE_AMB_SUII_JYOSHO,
			SE_AMB_SUII_KAKOU,
			SE_SYS_ONE_UP,
			SE_SYS_ONE_DOWN,
			SE_SYS_STOCK_ITEM,
			SE_SYS_STOCK_ITEM_USE,
			SE_SYS_RED_RING,
		};
	};

	NAMESPACE_ATTRIBUTE namespace SAR_VS_COMMON_LUIGI_BASE {
		enum {
			SE_PLY_SPIN_JUMP_L = FirstID::SAR_VS_COMMON_LUIGI_BASE,
			SE_PLY_KABE_KICK_L,
			SE_PLY_KABE_KICK_L_1,
			SE_PLY_KABE_KICK_L_2,
			SE_PLY_CHANGE_BIGGEST_L,
			SE_VOC_LU_JUMP_03,
			SE_VOC_LU_WIN,
			SE_VOC_LU_THROW,
			SE_VOC_LU_THROW_1,
		};
	};

	NAMESPACE_ATTRIBUTE namespace SAR_ITEM_HOUSE {
		enum {
			SE_OBJ_STICK = FirstID::SAR_ITEM_HOUSE,
			SE_OBJ_ITEM_SLOT,
			SE_OBJ_CARD_SET,
			SE_OBJ_BLOCK_SET,
			SE_OBJ_BLOCK_SHUFFLE,
			SE_EMY_KOOPA_LAUGH,
			SE_SYS_KABE_CHG,
		};
	};

	NAMESPACE_ATTRIBUTE namespace SAR_KOOPAJR_COMMON {
		enum {
			SE_EMY_KPJR_CHARGE_V = FirstID::SAR_KOOPAJR_COMMON,
			SE_EMY_KPJR_THROW_V,
			SE_EMY_KPJR_GAU,
			SE_EMY_KPJR_LAUGH,
			SE_EMY_KPJR_FOOTNOTE,
			SE_EMY_KPJR_JUMP,
			SE_VOC_JRDM_TRAIL,
			SE_VOC_JRDM_UN_02,
			SE_VOC_JRDM_UN_02_L,
			SE_VOC_JRDM_PEACH_CRY,
			SE_VOC_JRDM_PEACH_OH,
			SE_SYS_WIPE_1,
			SE_SYS_WIPE_2,
		};
	};

	NAMESPACE_ATTRIBUTE namespace SAR_PIPE_CANNON {
		enum {
			SE_OBJ_WDOKAN_APP = FirstID::SAR_PIPE_CANNON,
			SE_OBJ_WDOKAN_TILT_START,
			SE_OBJ_WDOKAN_TILT_END,
			SE_OBJ_WDOKAN_TURN,
			SE_PLY_KIRAAN,
		};
	};

	NAMESPACE_ATTRIBUTE namespace SAR_LAST_KOOPA_DOOR {
		enum {
			SE_OBJ_KPDOOR_OPEN = FirstID::SAR_LAST_KOOPA_DOOR,
			SE_OBJ_KPDOOR_MOVE,
			SE_OBJ_KPDOOR_CLOSE,
		};
	};

	NAMESPACE_ATTRIBUTE namespace SAR_LAST_KOOPA_DEMO {
		enum {
			SE_PLY_KISS = FirstID::SAR_LAST_KOOPA_DEMO,
			SE_EMY_KPJR_THROW,
			SE_OBJ_HONE_IN_TSUBO,
			SE_OBJ_TSUBO_GOTOGOTO,
			SE_OBJ_TSUBO_BREAK,
			SE_OBJ_TSUBO_EXPAND,
			SE_VOC_M_HOEE,
			SE_VOC_L_HOEE,
			SE_VOC_P_THANK_YOU,
		};
	};

	NAMESPACE_ATTRIBUTE namespace SAR_BOSS_COMMON {
		enum {
			SE_EMY_BOSS_DAMAGE = FirstID::SAR_BOSS_COMMON,
			SE_EMY_BOSS_FUMARE,
			SE_EMY_ELCJ_DOWN_2,
			SE_EMY_PUKU_HANE,
			SE_EMY_BOSS_HIP,
			SE_EMY_BOSS_DEATH,
			SE_OBJ_HIT_KOURA,
			SE_OBJ_KEY_APP,
			SE_OBJ_KEY_DROP,
		};
	};

	NAMESPACE_ATTRIBUTE namespace SAR_BOSS_CHOROPU {
		enum {
			SE_EMY_CHORO_THROW = FirstID::SAR_BOSS_CHOROPU,
			SE_EMY_CHORO_DOWN,
			SE_EMY_CHORO_SHOT,
			SE_EMY_CHORO_BOUSOU,
			SE_OBJ_CHORO_HOUDAI_TURN,
			SE_OBJ_CHORO_HOUDAI_GROW,
			SE_OBJ_BOMB_LAND,
			SE_AMB_CHORO_MOVE,
		};
	};

	NAMESPACE_ATTRIBUTE namespace SAR_OBJ_CORK {
		enum {
			SE_OBJ_CORK_PUSH = FirstID::SAR_OBJ_CORK,
			SE_OBJ_CORK_PULL,
			SE_OBJ_CORK_PON
		};
	};

}

#undef NAMESPACE_ATTRIBUTE
