#pragma once


namespace SeqPlayerID {

	enum {
		PLAYER_OF_BGM,
		ENEMY_MULTI_PLAYER = 2,
		ENEMY_PLAYER,
		ENEMY_PLAYER_2,
		ENEMY_PLAYER_3,
		PLAYER_PLAYER,
		PLAYER_PLAYER_2,
		AMB_PLAYER,
		VOICE_PLAYER,
		VOICE_PLAYER_2,
		SYSTEM_PLAYER,
		SYSTEM_PLAYER_2,
		OBJECT_PLAYER,
		OBJECT_PLAYER_2,
		OBJECT_PLAYER_3,
		OBJECT_PLAYER_4,
		OBJECT_PLAYER_5,
		OBJECT_PLAYER_6,
		OBJECT_PLAYER_7,
		OBJECT_PLAYER_8,
		ENEMY_PLAYER_4,
		ENEMY_PLAYER_5,
		ENEMY_PLAYER_6,
		PLAYER_PLAYER_3,
		SYSTEM_PLAYER_3,
		ENEMY_PLAYER_7,
		SYSTEM_PLAYER_4,

		Count
	};

}
