#pragma once

#include "nsmb_nitro.hpp"

#include "wireless_shared/mbp.hpp"
#include "wireless_shared/wfs.hpp"
#include "wireless_shared/wh.hpp"

#include "nsmb/boot.hpp"
#include "nsmb/ending.hpp"
#include "nsmb/entity.hpp"
#include "nsmb/filesystem.hpp"
#include "nsmb/game.hpp"
#include "nsmb/graphics.hpp"
#include "nsmb/math.hpp"
#include "nsmb/vsconnect.hpp"
#include "nsmb/physics.hpp"
#include "nsmb/player.hpp"
#include "nsmb/sound.hpp"
#include "nsmb/stage.hpp"
#include "nsmb/system.hpp"
#include "nsmb/titlescreen.hpp"
#include "nsmb/ui.hpp"
#include "nsmb/wifi.hpp"
#include "nsmb/world.hpp"
#include "nsmb/worldmap.hpp"
#include "nsmb/vendor.hpp"
#include "nsmb/extra.hpp"

#include "nsmb/scenes/corruptedsavescene.hpp"
